api:
  url: https://api.trace.moe
server:
  port: 8081
bot:
  name: AnimeRecognizerBot
  token: 6659045721:AAGU87XQyAZVU1sLTtNEStunAKD9ATDuekA
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic